<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Cliente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cliente_model');
    } 

    /*
     * Listing of clientes
     */
    function index()
    {
        $data['clientes'] = $this->Cliente_model->get_all_clientes();

        $data['_view'] = 'cliente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cliente
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('limite','Limite','numeric');
        $this->form_validation->set_rules('IDRevendedor','IDRevendedor','integer');
        $this->form_validation->set_rules('IDExecutiva','IDExecutiva','integer');
        $this->form_validation->set_rules('IDEmpresaria','IDEmpresaria','integer');

        if($this->form_validation->run())     
        {   
            $params = array(

                'IDCliente' => $this->input->post('IDCliente'),
                'limite' => $this->input->post('limite'),
            );
            
            $cliente_id = $this->Cliente_model->add_cliente($params);

            $params = array(

                'IDPreco' => $this->input->post('tabelaPreco'),
                'IDPessoa' => $this->input->post('IDCliente'),

            );

            $this->load->model('Precopessoa_model');
            $precopessoa_id = $this->Precopessoa_model->add_precopessoa($params);


            redirect('cliente/index');
        }
        else
        {   
            $this->load->model('Pessoa_model');
            $data['all_pessoas'] = $this->Pessoa_model->get_all_pessoas();   

            $this->load->model('Preco_model');
            $data['all_precos'] = $this->Preco_model->get_all_precos();

            $data['_view'] = 'cliente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cliente
     */
    function edit($IDCliente)
    {   
        // check if the cliente exists before trying to edit it
        $data['cliente'] = $this->Cliente_model->get_cliente($IDCliente);

        if(isset($data['cliente']['IDCliente']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('limite','Limite','numeric');
           

            if($this->form_validation->run())     
            {   
                $params = array(
                  
                    'limite' => $this->input->post('limite'),
                  
                );
                
                $this->Cliente_model->update_cliente($IDCliente,$params); 
                
                $params = array(
                  
                   'IDPreco' => $this->input->post('IDPreco'),
                  
                );
                  
                $this->load->model('Precopessoa_model');
                
                $precopessoa_id = $this->Precopessoa_model->update_precopessoa($IDCliente,$params);

                redirect('cliente/index');
                
            }
            else
            {   
                $this->load->model('Precopessoa_model');
                $data['pessoapreco'] = $this->Precopessoa_model->get_precopessoa($IDCliente);
                
                $this->load->model('Preco_model');
                $data['all_precos'] = $this->Preco_model->get_all_precos();
                
                $data['_view'] = 'cliente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cliente you are trying to edit does not exist.');
    } 

    /*
     * Deleting cliente
     */
    function remove($IDCliente)
    {
        $cliente = $this->Cliente_model->get_cliente($IDCliente);

        // check if the cliente exists before trying to delete it
        if(isset($cliente['IDCliente']))
        {
            $this->load->model('Precopessoa_model');
            $this->Precopessoa_model->delete_precopessoa($IDCliente);


            $this->Cliente_model->delete_cliente($IDCliente);
            redirect('cliente/index');
        }
        else
            show_error('The cliente you are trying to delete does not exist.');
    }

}
