<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grupo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Grupo_model');
         
        $user = $this->session->userdata();  
        
        if($user==false){ 
        
            redirect('login');
        
        }
    } 

    /*
     * Listing of grupos
     */
    function index()
    {
        $data['grupos'] = $this->Grupo_model->get_all_grupos();
        
        $data['_view'] = 'grupo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new grupo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('descricao','Descricao','max_length[45]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $grupo_id = $this->Grupo_model->add_grupo($params);
            redirect('grupo/index');
        }
        else
        {            
            $data['_view'] = 'grupo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a grupo
     */
    function edit($IDGrupo)
    {   
        // check if the grupo exists before trying to edit it
        $data['grupo'] = $this->Grupo_model->get_grupo($IDGrupo);
        
        if(isset($data['grupo']['IDGrupo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('descricao','Descricao','max_length[45]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Grupo_model->update_grupo($IDGrupo,$params);            
                redirect('grupo/index');
            }
            else
            {
                $data['_view'] = 'grupo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The grupo you are trying to edit does not exist.');
    } 

    /*
     * Deleting grupo
     */
    function remove($IDGrupo)
    {
        $grupo = $this->Grupo_model->get_grupo($IDGrupo);

        // check if the grupo exists before trying to delete it
        if(isset($grupo['IDGrupo']))
        {
            $this->Grupo_model->delete_grupo($IDGrupo);
            redirect('grupo/index');
        }
        else
            show_error('The grupo you are trying to delete does not exist.');
    }
    
}
