<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedidopagamento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pedidopagamento_model');
    } 

    /*
     * Listing of pedidopagamentos
     */
    function index()
    {
        $data['pedidopagamentos'] = $this->Pedidopagamento_model->get_all_pedidopagamentos();
        
        $data['_view'] = 'pedidopagamento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pedidopagamento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipoPagamento' => $this->input->post('tipoPagamento'),
				'dataPagamento' => $this->input->post('dataPagamento'),
				'valorParcela' => $this->input->post('valorParcela'),
            );
            
            $pedidopagamento_id = $this->Pedidopagamento_model->add_pedidopagamento($params);
            redirect('pedidopagamento/index');
        }
        else
        {
			$this->load->model('Tipopagamento_model');
			$data['all_tipopagamentos'] = $this->Tipopagamento_model->get_all_tipopagamentos();
            
            $data['_view'] = 'pedidopagamento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pedidopagamento
     */
    function edit($IDPedido)
    {   
        // check if the pedidopagamento exists before trying to edit it
        $data['pedidopagamento'] = $this->Pedidopagamento_model->get_pedidopagamento($IDPedido);
        
        if(isset($data['pedidopagamento']['IDPedido']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipoPagamento' => $this->input->post('tipoPagamento'),
					'dataPagamento' => $this->input->post('dataPagamento'),
					'valorParcela' => $this->input->post('valorParcela'),
                );

                $this->Pedidopagamento_model->update_pedidopagamento($IDPedido,$params);            
                redirect('pedidopagamento/index');
            }
            else
            {
				$this->load->model('Tipopagamento_model');
				$data['all_tipopagamentos'] = $this->Tipopagamento_model->get_all_tipopagamentos();

                $data['_view'] = 'pedidopagamento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pedidopagamento you are trying to edit does not exist.');
    } 

    /*
     * Deleting pedidopagamento
     */
    function remove($IDPedido)
    {
        $pedidopagamento = $this->Pedidopagamento_model->get_pedidopagamento($IDPedido);

        // check if the pedidopagamento exists before trying to delete it
        if(isset($pedidopagamento['IDPedido']))
        {
            $this->Pedidopagamento_model->delete_pedidopagamento($IDPedido);
            redirect('pedidopagamento/index');
        }
        else
            show_error('The pedidopagamento you are trying to delete does not exist.');
    }
    
}
