<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pessoatipo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pessoatipo_model');
    } 

    /*
     * Listing of pessoatipos
     */
    function index()
    {
        $data['pessoatipos'] = $this->Pessoatipo_model->get_all_pessoatipos();
        
        $data['_view'] = 'pessoatipo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pessoatipo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $pessoatipo_id = $this->Pessoatipo_model->add_pessoatipo($params);
            redirect('pessoatipo/index');
        }
        else
        {            
            $data['_view'] = 'pessoatipo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pessoatipo
     */
    function edit($IDPessoaTipo)
    {   
        // check if the pessoatipo exists before trying to edit it
        $data['pessoatipo'] = $this->Pessoatipo_model->get_pessoatipo($IDPessoaTipo);
        
        if(isset($data['pessoatipo']['IDPessoaTipo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Pessoatipo_model->update_pessoatipo($IDPessoaTipo,$params);            
                redirect('pessoatipo/index');
            }
            else
            {
                $data['_view'] = 'pessoatipo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pessoatipo you are trying to edit does not exist.');
    } 

    /*
     * Deleting pessoatipo
     */
    function remove($IDPessoaTipo)
    {
        $pessoatipo = $this->Pessoatipo_model->get_pessoatipo($IDPessoaTipo);

        // check if the pessoatipo exists before trying to delete it
        if(isset($pessoatipo['IDPessoaTipo']))
        {
            $this->Pessoatipo_model->delete_pessoatipo($IDPessoaTipo);
            redirect('pessoatipo/index');
        }
        else
            show_error('The pessoatipo you are trying to delete does not exist.');
    }
    
}
