<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Preco extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Preco_model');
        
         
        $user = $this->session->userdata();  
        
       if($user==false){ 
        
            redirect('login');
        
        }  
    } 

    /*
     * Listing of precos
     */
    function index()
    {
        $data['precos'] = $this->Preco_model->get_all_precos();
        
        $data['_view'] = 'preco/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new preco
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
				'comissao' => $this->input->post('comissao'),
            );
            
            $preco_id = $this->Preco_model->add_preco($params);
            redirect('preco/index');
        }
        else
        {            
            $data['_view'] = 'preco/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a preco
     */
    function edit($IDPreco)
    {   
        // check if the preco exists before trying to edit it
        $data['preco'] = $this->Preco_model->get_preco($IDPreco);
        
        if(isset($data['preco']['IDPreco']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
					'comissao' => $this->input->post('comissao'),
                );

                $this->Preco_model->update_preco($IDPreco,$params);            
                redirect('preco/index');
            }
            else
            {
                $data['_view'] = 'preco/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The preco you are trying to edit does not exist.');
    } 

    /*
     * Deleting preco
     */
    function remove($IDPreco)
    {
        $preco = $this->Preco_model->get_preco($IDPreco);

        // check if the preco exists before trying to delete it
        if(isset($preco['IDPreco']))
        {
            $this->Preco_model->delete_preco($IDPreco);
            redirect('preco/index');
        }
        else
            show_error('The preco you are trying to delete does not exist.');
    }
    
}
