<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Produto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Produto_model');
    } 

    /*
     * Listing of produtos
     */
    function index()
    {
        $data['produtos'] = $this->Produto_model->get_all_produtos();
        
        $data['_view'] = 'produto/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new produto
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'IDGrupo' => $this->input->post('IDGrupo'),
				'IDCategoria' => $this->input->post('IDCategoria'),
				'IDMarcas' => $this->input->post('IDMarcas'),
				'IDfornecedor' => $this->input->post('IDfornecedor'),
				'IDUnidade' => $this->input->post('IDUnidade'),
				'nome' => $this->input->post('nome'),
				'codigo' => $this->input->post('codigo'),
				'precoCusto' => $this->input->post('precoCusto'),
				'precoVenda' => $this->input->post('precoVenda'),
				'situacao' => $this->input->post('situacao'),
				'descricao' => $this->input->post('descricao'),
				'codBarras' => $this->input->post('codBarras'),
				'foto' => $this->input->post('foto'),
				'dataCadastro' => $this->input->post('dataCadastro'),
            );
            
            $produto_id = $this->Produto_model->add_produto($params);
            redirect('produto/index');
        }
        else
        {
			$this->load->model('Grupo_model');
			$data['all_grupos'] = $this->Grupo_model->get_all_grupos();

			$this->load->model('Categoria_model');
			$data['all_categorias'] = $this->Categoria_model->get_all_categorias();

			$this->load->model('Marca_model');
			$data['all_marcas'] = $this->Marca_model->get_all_marcas();

			$this->load->model('Fornecedor_model');
			$data['all_fornecedores'] = $this->Fornecedor_model->get_all_fornecedores();

			$this->load->model('Unidade_model');
			$data['all_unidades'] = $this->Unidade_model->get_all_unidades();
            
            $data['_view'] = 'produto/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a produto
     */
    function edit($IDProduto)
    {   
        // check if the produto exists before trying to edit it
        $data['produto'] = $this->Produto_model->get_produto($IDProduto);
        
        if(isset($data['produto']['IDProduto']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'IDGrupo' => $this->input->post('IDGrupo'),
					'IDCategoria' => $this->input->post('IDCategoria'),
					'IDMarcas' => $this->input->post('IDMarcas'),
					'IDfornecedor' => $this->input->post('IDfornecedor'),
					'IDUnidade' => $this->input->post('IDUnidade'),
					'nome' => $this->input->post('nome'),
					'codigo' => $this->input->post('codigo'),
					'precoCusto' => $this->input->post('precoCusto'),
					'precoVenda' => $this->input->post('precoVenda'),
					'situacao' => $this->input->post('situacao'),
					'descricao' => $this->input->post('descricao'),
					'codBarras' => $this->input->post('codBarras'),
					'foto' => $this->input->post('foto'),
					'dataCadastro' => $this->input->post('dataCadastro'),
                );

                $this->Produto_model->update_produto($IDProduto,$params);            
                redirect('produto/index');
            }
            else
            {
				$this->load->model('Grupo_model');
				$data['all_grupos'] = $this->Grupo_model->get_all_grupos();

				$this->load->model('Categoria_model');
				$data['all_categorias'] = $this->Categoria_model->get_all_categorias();

				$this->load->model('Marca_model');
				$data['all_marcas'] = $this->Marca_model->get_all_marcas();

				$this->load->model('Fornecedor_model');
				$data['all_fornecedores'] = $this->Fornecedor_model->get_all_fornecedores();

				$this->load->model('Unidade_model');
				$data['all_unidades'] = $this->Unidade_model->get_all_unidades();

                $data['_view'] = 'produto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The produto you are trying to edit does not exist.');
    } 

    /*
     * Deleting produto
     */
    function remove($IDProduto)
    {
        $produto = $this->Produto_model->get_produto($IDProduto);

        // check if the produto exists before trying to delete it
        if(isset($produto['IDProduto']))
        {
            $this->Produto_model->delete_produto($IDProduto);
            redirect('produto/index');
        }
        else
            show_error('The produto you are trying to delete does not exist.');
    }
    
}
