<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Revendedor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Revendedor_model');
    } 

    /*
     * Listing of revendedores
     */
    function index()
    {
        $data['revendedores'] = $this->Revendedor_model->get_all_revendedores();
        
        $data['_view'] = 'revendedor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new revendedor
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                
				'IDRevendedor' => $this->input->post('IDRevendedor'),
				'tabelaPreco' => $this->input->post('tabelaPreco'),
				//'IDEmpresaria' => $this->input->post('IDEmpresaria'),
				//'IDExecutiva' => $this->input->post('IDExecutiva'),
				'limite' => $this->input->post('limite'),
            );
            
            $revendedor_id = $this->Revendedor_model->add_revendedor($params);
            redirect('revendedor/index');
        }
        else
        {
            $this->load->model('Pessoa_model');
			$data['all_pessoas'] = $this->Pessoa_model->get_all_pessoas();
            
			$this->load->model('Preco_model');
			$data['all_precos'] = $this->Preco_model->get_all_precos();

			$this->load->model('Empresaria_model');
			$data['all_empresarias'] = $this->Empresaria_model->get_all_empresarias();

			$this->load->model('Executiva_model');
			$data['all_executivas'] = $this->Executiva_model->get_all_executivas();
            
            $data['_view'] = 'revendedor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a revendedor
     */
    function edit($IDRevendedor)
    {   
        // check if the revendedor exists before trying to edit it
        $data['revendedor'] = $this->Revendedor_model->get_revendedor($IDRevendedor);
        
        if(isset($data['revendedor']['IDRevendedor']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tabelaPreco' => $this->input->post('tabelaPreco'),
					'IDEmpresaria' => $this->input->post('IDEmpresaria'),
					'IDExecutiva' => $this->input->post('IDExecutiva'),
					'limite' => $this->input->post('limite'),
                );

                $this->Revendedor_model->update_revendedor($IDRevendedor,$params);            
                redirect('revendedor/index');
            }
            else
            {
				$this->load->model('Preco_model');
				$data['all_precos'] = $this->Preco_model->get_all_precos();

				$this->load->model('Empresaria_model');
				$data['all_empresarias'] = $this->Empresaria_model->get_all_empresarias();

				$this->load->model('Executiva_model');
				$data['all_executivas'] = $this->Executiva_model->get_all_executivas();

                $data['_view'] = 'revendedor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The revendedor you are trying to edit does not exist.');
    } 

    /*
     * Deleting revendedor
     */
    function remove($IDRevendedor)
    {
        $revendedor = $this->Revendedor_model->get_revendedor($IDRevendedor);

        // check if the revendedor exists before trying to delete it
        if(isset($revendedor['IDRevendedor']))
        {
            $this->Revendedor_model->delete_revendedor($IDRevendedor);
            redirect('revendedor/index');
        }
        else
            show_error('The revendedor you are trying to delete does not exist.');
    }
    
}
