<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Situacaopedido extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Situacaopedido_model');
    } 

    /*
     * Listing of situacaopedidos
     */
    function index()
    {
        $data['situacaopedidos'] = $this->Situacaopedido_model->get_all_situacaopedidos();
        
        $data['_view'] = 'situacaopedido/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new situacaopedido
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $situacaopedido_id = $this->Situacaopedido_model->add_situacaopedido($params);
            redirect('situacaopedido/index');
        }
        else
        {            
            $data['_view'] = 'situacaopedido/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a situacaopedido
     */
    function edit($IDSituacao)
    {   
        // check if the situacaopedido exists before trying to edit it
        $data['situacaopedido'] = $this->Situacaopedido_model->get_situacaopedido($IDSituacao);
        
        if(isset($data['situacaopedido']['IDSituacao']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Situacaopedido_model->update_situacaopedido($IDSituacao,$params);            
                redirect('situacaopedido/index');
            }
            else
            {
                $data['_view'] = 'situacaopedido/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The situacaopedido you are trying to edit does not exist.');
    } 

    /*
     * Deleting situacaopedido
     */
    function remove($IDSituacao)
    {
        $situacaopedido = $this->Situacaopedido_model->get_situacaopedido($IDSituacao);

        // check if the situacaopedido exists before trying to delete it
        if(isset($situacaopedido['IDSituacao']))
        {
            $this->Situacaopedido_model->delete_situacaopedido($IDSituacao);
            redirect('situacaopedido/index');
        }
        else
            show_error('The situacaopedido you are trying to delete does not exist.');
    }
    
}
