<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipopedido extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipopedido_model');
         $user = $this->session->userdata();  
        
        $row = count($user);      
              
        if($row==1){     
            
            redirect('login');
        }
    } 

    /*
     * Listing of tipopedidos
     */
    function index()
    {
        $data['tipopedidos'] = $this->Tipopedido_model->get_all_tipopedidos();
        
        $data['_view'] = 'tipopedido/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipopedido
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'Descricao' => $this->input->post('Descricao'),
            );
            
            $tipopedido_id = $this->Tipopedido_model->add_tipopedido($params);
            redirect('tipopedido/index');
        }
        else
        {            
            $data['_view'] = 'tipopedido/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipopedido
     */
    function edit($IDTipoPedido)
    {   
        // check if the tipopedido exists before trying to edit it
        $data['tipopedido'] = $this->Tipopedido_model->get_tipopedido($IDTipoPedido);
        
        if(isset($data['tipopedido']['IDTipoPedido']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'Descricao' => $this->input->post('Descricao'),
                );

                $this->Tipopedido_model->update_tipopedido($IDTipoPedido,$params);            
                redirect('tipopedido/index');
            }
            else
            {
                $data['_view'] = 'tipopedido/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipopedido you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipopedido
     */
    function remove($IDTipoPedido)
    {
        $tipopedido = $this->Tipopedido_model->get_tipopedido($IDTipoPedido);

        // check if the tipopedido exists before trying to delete it
        if(isset($tipopedido['IDTipoPedido']))
        {
            $this->Tipopedido_model->delete_tipopedido($IDTipoPedido);
            redirect('tipopedido/index');
        }
        else
            show_error('The tipopedido you are trying to delete does not exist.');
    }
    
}
