<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        
    }
    
    /*
     * Get cliente by IDCliente
     */
    function get_cliente($IDCliente)
        
    {
        $this->db->join('pessoa', 'pessoa.IDPessoa = cliente.IDCliente');
        return $this->db->get_where('Cliente',array('IDCliente'=>$IDCliente))->row_array();
    }
        
    /*
     * Get all clientes
     */
    function get_all_clientes()
        
    {   
        $this->db->join('pessoa', 'pessoa.IDPessoa = cliente.IDCliente');
        $this->db->order_by('IDCliente', 'desc');
        return $this->db->get('Cliente')->result_array();
    }
        
    /*
     * function to add new cliente
     */
    function add_cliente($params)
    {
        $this->db->insert('Cliente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cliente
     */
    function update_cliente($IDCliente,$params)
    {
        $this->db->where('IDCliente',$IDCliente);
        return $this->db->update('Cliente',$params);
    }
    
    /*
     * function to delete cliente
     */
    function delete_cliente($IDCliente)
    {
        return $this->db->delete('Cliente',array('IDCliente'=>$IDCliente));
    }
}
