<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empresaria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
      
    }
    
    /*
     * Get empresaria by IDEmpresaria
     */
    function get_empresaria($IDEmpresaria)
    {           
         $this->db->join('pessoa', 'pessoa.IDPessoa = empresaria.IDEmpresaria');
        return $this->db->get_where('empresaria',array('IDEmpresaria'=>$IDEmpresaria))->row_array();
    }
        
    /*
     * Get all empresarias
     */
    function get_all_empresarias()
    {   
        $this->db->join('pessoa', 'pessoa.IDPessoa = empresaria.IDEmpresaria');
        $this->db->order_by('IDEmpresaria', 'desc');
        return $this->db->get('empresaria')->result_array();
    }
        
    /*
     * function to add new empresaria
     */
    function add_empresaria($params)
    {
        $this->db->insert('empresaria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update empresaria
     */
    function update_empresaria($IDEmpresaria,$params)
    {
        $this->db->where('IDEmpresaria',$IDEmpresaria);
        return $this->db->update('empresaria',$params);
    }
    
    /*
     * function to delete empresaria
     */
    function delete_empresaria($IDEmpresaria)
    {
        return $this->db->delete('empresaria',array('IDEmpresaria'=>$IDEmpresaria));
    }
}
