<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Endereco_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get endereco by IDEndereco
     */
    function get_endereco($IDPessoa)
    {
        return $this->db->get_where('endereco',array('IDPessoa'=>$IDPessoa))->row_array();
    }
        
    /*
     * Get all enderecos
     */
    function get_all_enderecos()
    {
        $this->db->order_by('IDEndereco', 'desc');
        return $this->db->get('endereco')->result_array();
    }
        
    /*
     * function to add new endereco
     */
    function add_endereco($params)
    {
        $this->db->insert('endereco',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update endereco
     */
    function update_endereco($IDEndereco,$params)
    {
        $this->db->where('IDPessoa',$IDEndereco);
        return $this->db->update('endereco',$params);
    }
    
    /*
     * function to delete endereco
     */
    function delete_endereco($IDEndereco)
        
    {
        return $this->db->delete('endereco',array('IDPessoa'=>$IDEndereco));
    }
}
