<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estoque_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estoque by IDEstoque
     */
    function get_estoque($IDEstoque)
    {
        return $this->db->get_where('estoque',array('IDEstoque'=>$IDEstoque))->row_array();
    }
        
    /*
     * Get all estoques
     */
    function get_all_estoques()
    {
       
        $this->db->join ( 'produto' ,  'produto.IDProduto = estoque.IDProduto' ); 
        $this->db->order_by('IDEstoque', 'desc');
        return $this->db->get('estoque')->result_array();
    }
        
    /*
     * function to add new estoque
     */
    function add_estoque($params)
    {
        $this->db->insert('est_saida_produto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estoque
     */
    function update_estoque($IDEstoque,$params)
    {
        $this->db->where('est_saida_produto',$IDEstoque);
        return $this->db->update('estoque',$params);
    }
    
    /*
     * function to delete estoque
     */
    function delete_estoque($IDEstoque)
    {
        return $this->db->delete('est_saida_produto',array('IDPedido'=>$IDEstoque));
    }
}
