<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estoque_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estoque by IDEstoque
     */
    function get_estoque($IDEstoque)
    {
        return $this->db->get_where('Estoque',array('IDEstoque'=>$IDEstoque))->row_array();
    }
        
    /*
     * Get all estoques
     */
    function get_all_estoques()
    {
        $this->db->order_by('IDEstoque', 'desc');
        return $this->db->get('Estoque')->result_array();
    }
        
    /*
     * function to add new estoque
     */
    function add_estoque($params)
    {
        $this->db->insert('Estoque',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estoque
     */
    function update_estoque($IDEstoque,$params)
    {
        $this->db->where('IDEstoque',$IDEstoque);
        return $this->db->update('Estoque',$params);
    }
    
    /*
     * function to delete estoque
     */
    function delete_estoque($IDEstoque)
    {
        return $this->db->delete('Estoque',array('IDEstoque'=>$IDEstoque));
    }
}
