<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Executiva_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get executiva by IDExecutiva
     */
    function get_executiva($IDExecutiva)
    {           
                $this->db->join('pessoa', 'pessoa.IDPessoa = executiva.IDExecutiva');
        return $this->db->get_where('executiva',array('IDExecutiva'=>$IDExecutiva))->row_array();
    }
        
    /*
     * Get all executivas
     */
    function get_all_executivas()
    {
        $this->db->join('pessoa', 'pessoa.IDPessoa = executiva.IDExecutiva');
        $this->db->order_by('IDExecutiva', 'desc');
        return $this->db->get('executiva')->result_array();
    }
        
    /*
     * function to add new executiva
     */
    function add_executiva($params)
    {
        $this->db->insert('executiva',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update executiva
     */
    function update_executiva($IDExecutiva,$params)
    {
        $this->db->where('IDExecutiva',$IDExecutiva);
        return $this->db->update('executiva',$params);
    }
    
    /*
     * function to delete executiva
     */
    function delete_executiva($IDExecutiva)
    {
        return $this->db->delete('executiva',array('IDExecutiva'=>$IDExecutiva));
    }
}
