<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fechamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        
    }
    
    /*
     * Get categoria by IDfechamento
     */
    function get_fechamento($IDFechamento)
    {
        return $this->db->get_where('fechamentoconsignado',array('IDfechamento'=>$IDFechamento))->row_array();
    }
        
    /*
     * Get all fechamentos
     */
    function get_all_fechamentos()
    {
        $this->db->join('pessoa', 'pessoa.IDPessoa = fechamentoconsignado.IDPessoa');
        $this->db->order_by('IDFechamento', 'desc');
        return $this->db->get('fechamentoconsignado')->result_array();
    }
        
    /*
     * function to add new fechamento
     */
    function add_fechamento($params)
    {
        $this->db->insert('fechamentoconsignado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fechamento
     */
    function update_fechamento($IDFechamento,$params)
    {
        $this->db->where('IDFechamento',$IDFechamento);
        return $this->db->update('fechamentoconsignado',$params);
    }
    
    /*
     * function to delete fechamento
     */
    function delete_fechamento($IDfechamento)
    {
        return $this->db->delete('fechamentoconsignado',array('IDfechamento'=>$IDFechamento));
    }
    
    function gerar_financeiro(){
        
        
        
        
    }
    
    
    
    
    
}
