<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Filial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        
    }
    
    /*
     * Get filial by IDFilial
     */
    function get_filial($IDFilial)
    {
        return $this->db->get_where('filial',array('IDFilial'=>$IDFilial))->row_array();
    }
        
    /*
     * Get all filiais
     */
    function get_all_filiais()
    {
        $this->db->order_by('IDFilial', 'desc');
        return $this->db->get('filial')->result_array();
    }
        
    /*
     * function to add new filial
     */
    function add_filial($params)
    {
        $this->db->insert('filial',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update filial
     */
    function update_filial($IDFilial,$params)
    {
        $this->db->where('IDFilial',$IDFilial);
        return $this->db->update('filial',$params);
    }
    
    /*
     * function to delete filial
     */
    function delete_filial($IDFilial)
    {
        return $this->db->delete('filial',array('IDFilial'=>$IDFilial));
    }
}
