<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grupo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        
    }
    
    /*
     * Get grupo by IDGrupo
     */
    function get_grupo($IDGrupo)
    {
        return $this->db->get_where('grupo',array('IDGrupo'=>$IDGrupo))->row_array();
    }
        
    /*
     * Get all grupos
     */
    function get_all_grupos()
    {
        $this->db->order_by('IDGrupo', 'desc');
        return $this->db->get('grupo')->result_array();
    }
        
    /*
     * function to add new grupo
     */
    function add_grupo($params)
    {
        $this->db->insert('grupo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update grupo
     */
    function update_grupo($IDGrupo,$params)
    {
        $this->db->where('IDGrupo',$IDGrupo);
        return $this->db->update('grupo',$params);
    }
    
    /*
     * function to delete grupo
     */
    function delete_grupo($IDGrupo)
    {
        return $this->db->delete('grupo',array('IDGrupo'=>$IDGrupo));
    }
}
