<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Login_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        
    }

    /*
     * Get marca by IDMarcas
     */
    function get_user($email,$senha)

    {
        $this->db->select('id,username');
        $this->db->where('email',$email);
        $this->db->where('password',$senha);
        $usuario = $this->db->get('users')->row_array();
        return $usuario;
        
     
        
    }

}