<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pedido by IDPedido
     */
    function get_pedido($IDPedido)
    {
        return $this->db->get_where('Pedido',array('IDPedido'=>$IDPedido))->row_array();
    }
        
    /*
     * Get all pedidos
     */
    function get_all_pedidos()
    {
        $this->db->order_by('IDPedido', 'desc');
        return $this->db->get('Pedido')->result_array();
    }
        
    /*
     * function to add new pedido
     */
    function add_pedido($params)
    {
        $this->db->insert('Pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedido
     */
    function update_pedido($IDPedido,$params)
    {
        $this->db->where('IDPedido',$IDPedido);
        return $this->db->update('Pedido',$params);
    }
    
    /*
     * function to delete pedido
     */
    function delete_pedido($IDPedido)
    {
        return $this->db->delete('Pedido',array('IDPedido'=>$IDPedido));
    }
}
