<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
       
        
    }
    
    /*
     * Get pedido by IDPedido
     */
    function get_pedido($IDPedido)
    {
        return $this->db->get_where('Pedido',array('IDPedido'=>$IDPedido))->row_array();
    }
  
    /*
     * Get all pedidos
     */
    function get_all_pedidos()
    {
        
        $this->db->select ( '*' ); 
        $this->db->from ( 'pedido' ); 
        $this->db->join ( 'pessoa' ,  'pedido.IDPessoa = pessoa.IDPessoa' );        
        $this->db->join ( 'tipopagamento' ,  'pedido.tipoPagamento = tipopagamento.IDTipoPagamento' );      
        $this->db->join ( 'tipopedido' ,  'pedido.tipoPedido = tipopedido.IDTipoPedido' );      
              
        $this->db->order_by('IDPedido', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new pedido
     */
    function add_pedido($params)
    {
        $this->db->insert('Pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedido
     */
    function update_pedido($IDPedido,$params)
    {
        $this->db->where('IDPedido',$IDPedido);
        return $this->db->update('Pedido',$params);
    }
    
    /*
     * function to delete pedido
     */
    function delete_pedido($IDPedido)
    {
        return $this->db->delete('Pedido',array('IDPedido'=>$IDPedido));
    }
    
    
    
       public function autoCompleteProduto($q)
    {

        $this->db->select('*');
        $this->db->limit(5);
        $this->db->like('nome', $q);
        $query = $this->db->get('produto');
        if ($query->num_rows() > 0) {
            foreach ($query->result_array() as $row) {
                $row_set[] = array('label'=>$row['descricao'].' | Preço: R$ '.$row['precoVenda'],'id'=>$row['IDProduto'],'preco'=>$row['precoVenda']);
            }
            echo json_encode($row_set);
        }
    }

    public function autoCompleteCliente($q)
    {

        $this->db->select('*');
        $this->db->limit(5);
        $this->db->like('nomeCliente', $q);
        $query = $this->db->get('clientes');
        if ($query->num_rows() > 0) {
            foreach ($query->result_array() as $row) {
                $row_set[] = array('label'=>$row['nomeCliente'].' | Telefone: '.$row['telefone'],'id'=>$row['idClientes']);
            }
            echo json_encode($row_set);
        }
    }
}
