<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
       
        
    }
    
    /*
     * Get pedido by IDPedido
     */
    function get_pedido($IDPedido)
    {
                $this->db->join ( 'pessoa' ,  'pedido.IDPessoa = pessoa.IDPessoa' );    
        return $this->db->get_where('pedido',array('IDPedido'=>$IDPedido))->row_array();
    }
  
    /*
     * Get all pedidos
     */
    function get_all_pedidos()
    {
        
        $this->db->select ( '*' ); 
        $this->db->from ( 'pedido' ); 
        $this->db->join ( 'pessoa' ,  'pedido.IDPessoa = pessoa.IDPessoa' );        
        $this->db->join ( 'tipopagamento' ,  'pedido.tipoPagamento = tipopagamento.IDTipoPagamento' );      
        $this->db->join ( 'tipopedido' ,  'pedido.tipoPedido = tipopedido.IDTipoPedido' );      
              
        $this->db->order_by('IDPedido', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new pedido
     */
    function add_pedido($params)
    {
        $this->db->insert('pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedido
     */
    function update_pedido($IDPedido,$params)
    {
        $this->db->where('IDPedido',$IDPedido);
        return $this->db->update('pedido',$params);
    }
    
    /*
     * function to delete pedido
     */
    function delete_pedido($IDPedido)
    {
        return $this->db->delete('pedido',array('IDPedido'=>$IDPedido));
    }
    
    

}
