<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedidoitem_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pedidoitem by IDPedidoItens
     */
    function get_pedidoitem($IDPedidoItens)
    {
        return $this->db->get_where('pedidoitens',array('IDPedidoItens'=>$IDPedidoItens))->result_array();
    }
        
    /*
     * Get all pedidoitens
     */
    function get_all_pedidoitens()
    {
        $this->db->order_by('IDPedidoItens', 'desc');
        return $this->db->get('pedidoitens')->result_array();
    }
        
    /*
     * function to add new pedidoitem
     */
    function add_pedidoitem($params)
    {
        $this->db->insert('pedidoitens',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedidoitem
     */
    function update_pedidoitem($IDPedidoItens,$params)
    {
        $this->db->where('IDPedidoItens',$IDPedidoItens);
        return $this->db->update('pedidoitens',$params);
    }
    
    /*
     * function to delete pedidoitem
     */
    function delete_pedidoitem($IDPedidoItens)
    {
        return $this->db->delete('pedidoitens',array('IDPedidoItens'=>$IDPedidoItens));
    }
}
