<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedidopagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pedidopagamento by IDPedido
     */
    function get_pedidopagamento($IDPedido)
    {
        return $this->db->get_where('PedidoPagamento',array('IDPedido'=>$IDPedido))->row_array();
    }
        
    /*
     * Get all pedidopagamentos
     */
    function get_all_pedidopagamentos()
    {
        $this->db->order_by('IDPedido', 'desc');
        return $this->db->get('PedidoPagamento')->result_array();
    }
        
    /*
     * function to add new pedidopagamento
     */
    function add_pedidopagamento($params)
    {
        $this->db->insert('PedidoPagamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedidopagamento
     */
    function update_pedidopagamento($IDPedido,$params)
    {
        $this->db->where('IDPedido',$IDPedido);
        return $this->db->update('PedidoPagamento',$params);
    }
    
    /*
     * function to delete pedidopagamento
     */
    function delete_pedidopagamento($IDPedido)
    {
        return $this->db->delete('PedidoPagamento',array('IDPedido'=>$IDPedido));
    }
}
