<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pessoajuridica_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pessoajuridica by IDPessoaJuridica
     */
    function get_pessoajuridica($IDPessoa)
    {
        return $this->db->get_where('pessoajuridica',array('IDPessoaJuridica'=>$IDPessoa))->row_array();
    }
        
    /*
     * Get all pessoajuridicas
     */
    function get_all_pessoajuridicas()
    {
        $this->db->order_by('IDPessoaJuridica', 'desc');
        return $this->db->get('pessoajuridica')->result_array();
    }
        
    /*
     * function to add new pessoajuridica
     */
    function add_pessoajuridica($params)
    {
        $this->db->insert('pessoajuridica',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pessoajuridica
     */
    function update_pessoajuridica($IDPessoaJuridica,$params)
    {
        $this->db->where('IDPessoaJuridica', $IDPessoaJuridica);
        return $this->db->update('pessoajuridica',$params);
    }
    
    /*
     * function to delete pessoajuridica
     */
    function delete_pessoajuridica($IDPessoaJuridica)
    {
        return $this->db->delete('pessoajuridica',array('IDPessoaJuridica'=>$IDPessoaJuridica));
    }
}
