<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pessoa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        
    }
    
    /*
     * Get pessoa by IDPessoa
     */
    function get_pessoa($IDPessoa)
    {
                             
        return $this->db->get_where('pessoa',array('IDPessoa'=>$IDPessoa))->row_array();
        
    }
    
   
    /*
     * Get all pessoas
     */
    function get_all_pessoas()
        
    {        
        $this->db->select ( '*' ); 
        $this->db->from ( 'pessoa' ); 
        $this->db->join ( 'pessoatipo' ,  'pessoa.IDPessoaTipo = pessoatipo.IDPessoaTipo' ); 
        $this->db->order_by('IDPessoa', 'desc');
        return $query=$this->db->get ()->result_array();
    }
    
    function get_pessoas_semCad()
        
    {        
        $this->db->select ( '*' ); 
        $this->db->from ( 'pessoa' ); 
        $this->db->where('IDTipoCadastro',0);
        $this->db->join ( 'pessoatipo' ,  'pessoa.IDPessoaTipo = pessoatipo.IDPessoaTipo' ); 
        $this->db->order_by('IDPessoa', 'desc');
        return $query=$this->db->get ()->result_array();;
    }
    /*
     * function to add new pessoa
     */
    function add_pessoa($params)
    {
        $this->db->insert('pessoa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pessoa
     */
    function update_pessoa($IDPessoa,$params)
    {
        $this->db->where('IDPessoa',$IDPessoa);
        return $this->db->update('pessoa',$params);
    }
    
    /*
     * function to delete pessoa
     */
    function delete_pessoa($IDPessoa)
    {
        return $this->db->delete('pessoa',array('IDPessoa'=>$IDPessoa));
    }
}
