<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prazopagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get prazopagamento by IDPrazoPag
     */
    function get_prazopagamento($IDPrazoPag)
    {
        return $this->db->get_where('PrazoPagamento',array('IDPrazoPag'=>$IDPrazoPag))->row_array();
    }
        
    /*
     * Get all prazopagamentos
     */
    function get_all_prazopagamentos()
    {
        $this->db->order_by('IDPrazoPag', 'desc');
        return $this->db->get('PrazoPagamento')->result_array();
    }
        
    /*
     * function to add new prazopagamento
     */
    function add_prazopagamento($params)
    {
        $this->db->insert('PrazoPagamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update prazopagamento
     */
    function update_prazopagamento($IDPrazoPag,$params)
    {
        $this->db->where('IDPrazoPag',$IDPrazoPag);
        return $this->db->update('PrazoPagamento',$params);
    }
    
    /*
     * function to delete prazopagamento
     */
    function delete_prazopagamento($IDPrazoPag)
    {
        return $this->db->delete('PrazoPagamento',array('IDPrazoPag'=>$IDPrazoPag));
    }
}
