<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Precoproduto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get precoproduto by IDPreco
     */
    function get_precoproduto($IDPreco)
    {
        return $this->db->get_where('precoproduto',array('IDPreco'=>$IDPreco))->row_array();
    }
        
    /*
     * Get all precoprodutos
     */
    function get_all_precoprodutos()
    {
        $this->db->order_by('IDPreco', 'desc');
        return $this->db->get('precoproduto')->result_array();
    }
        
    /*
     * function to add new precoproduto
     */
    function add_precoproduto($params)
    {
        $this->db->insert('precoproduto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update precoproduto
     */
    function update_precoproduto($IDPreco,$params)
    {
        $this->db->where('IDPreco',$IDPreco);
        return $this->db->update('precoproduto',$params);
    }
    
    /*
     * function to delete precoproduto
     */
    function delete_precoproduto($IDPreco)
    {
        return $this->db->delete('precoproduto',array('IDPreco'=>$IDPreco));
    }
}
