<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Produto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();


    }

    /*
     * Get produto by IDProduto
     */
    function get_produto($IDProduto)
    {
        return $this->db->get_where('Produto',array('IDProduto'=>$IDProduto))->row_array();
    }

    function get_like_produto($busca)   
    {
        $this->db->select('IDProduto,nome');
        $this->db->from('produto');
        $this->db->like("nome","$busca");
        $query=$this->db->get()->result_array(); 
        $row = $this->db->affected_rows();
        if ( $row > 0){            
            $retorno['produto'] = $query;
            $retorno['qtd']=$row;
           return json_encode($retorno);
        }else
        {
            $msg = false;
            return json_encode($msg);
        }

    }


    /*
     * Get all produtos
     */
    function get_all_produtos()
    {
        $this->db->order_by('IDProduto', 'desc');
        return $this->db->get('Produto')->result_array();
    }

    /*
     * function to add new produto
     */
    function add_produto($params)
    {
        $this->db->insert('Produto',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update produto
     */
    function update_produto($IDProduto,$params)
    {
        $this->db->where('IDProduto',$IDProduto);
        return $this->db->update('Produto',$params);
    }

    /*
     * function to delete produto
     */
    function delete_produto($IDProduto)
    {
        return $this->db->delete('Produto',array('IDProduto'=>$IDProduto));
    }
}
