<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Produto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();


    }

    /*
     * Get produto by IDProduto
     */
    function get_produto($IDProduto)
    {
        return $this->db->get_where('produto',array('IDProduto'=>$IDProduto))->row_array();
    }

    function get_like_produto($busca)   
    {
        $this->db->select('IDProduto,nome_produto');
        $this->db->from('produto');
        $this->db->like("nome_produto","$busca");
        $query=$this->db->get()->result_array(); 
        $row = $this->db->affected_rows();        
        if ( $row > 0){  
            
            $retorno = $query;
           
           return ($retorno);
        }else
        {
            $retorno = false;
            return ($retorno);
        }

    }


    /*
     * Get all produtos
     */
    function get_all_produtos()
    {
        $this->db->order_by('IDProduto', 'desc');
        return $this->db->get('produto')->result_array();
    }

    /*
     * function to add new produto
     */
    function add_produto($params)
    {
        $this->db->insert('produto',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update produto
     */
    function update_produto($IDProduto,$params)
    {
        $this->db->where('IDProduto',$IDProduto);
        return $this->db->update('produto',$params);
    }

    /*
     * function to delete produto
     */
    function delete_produto($IDProduto)
    {
        return $this->db->delete('produto',array('IDProduto'=>$IDProduto));
    }
}
