<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Situacaopedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get situacaopedido by IDSituacao
     */
    function get_situacaopedido($IDSituacao)
    {
        return $this->db->get_where('situacaoPedido',array('IDSituacao'=>$IDSituacao))->row_array();
    }
        
    /*
     * Get all situacaopedidos
     */
    function get_all_situacaopedidos()
    {
        $this->db->order_by('IDSituacao', 'desc');
        return $this->db->get('situacaoPedido')->result_array();
    }
        
    /*
     * function to add new situacaopedido
     */
    function add_situacaopedido($params)
    {
        $this->db->insert('situacaoPedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update situacaopedido
     */
    function update_situacaopedido($IDSituacao,$params)
    {
        $this->db->where('IDSituacao',$IDSituacao);
        return $this->db->update('situacaoPedido',$params);
    }
    
    /*
     * function to delete situacaopedido
     */
    function delete_situacaopedido($IDSituacao)
    {
        return $this->db->delete('situacaoPedido',array('IDSituacao'=>$IDSituacao));
    }
}
