<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipopagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipopagamento by IDTipoPagamento
     */
    function get_tipopagamento($IDTipoPagamento)
    {
        return $this->db->get_where('tipopagamento',array('IDTipoPagamento'=>$IDTipoPagamento))->row_array();
    }
        
    /*
     * Get all tipopagamentos
     */
    function get_all_tipopagamentos()
    {
        $this->db->order_by('IDTipoPagamento', 'desc');
        return $this->db->get('tipopagamento')->result_array();
    }
        
    /*
     * function to add new tipopagamento
     */
    function add_tipopagamento($params)
    {
        $this->db->insert('tipopagamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipopagamento
     */
    function update_tipopagamento($IDTipoPagamento,$params)
    {
        $this->db->where('IDTipoPagamento',$IDTipoPagamento);
        return $this->db->update('tipopagamento',$params);
    }
    
    /*
     * function to delete tipopagamento
     */
    function delete_tipopagamento($IDTipoPagamento)
    {
        return $this->db->delete('tipopagamento',array('IDTipoPagamento'=>$IDTipoPagamento));
    }
}
