<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipopedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipopedido by IDTipoPedido
     */
    function get_tipopedido($IDTipoPedido)
    {
        return $this->db->get_where('TipoPedido',array('IDTipoPedido'=>$IDTipoPedido))->row_array();
    }
        
    /*
     * Get all tipopedidos
     */
    function get_all_tipopedidos()
    {
        $this->db->order_by('IDTipoPedido', 'desc');
        return $this->db->get('TipoPedido')->result_array();
    }
        
    /*
     * function to add new tipopedido
     */
    function add_tipopedido($params)
    {
        $this->db->insert('TipoPedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipopedido
     */
    function update_tipopedido($IDTipoPedido,$params)
    {
        $this->db->where('IDTipoPedido',$IDTipoPedido);
        return $this->db->update('TipoPedido',$params);
    }
    
    /*
     * function to delete tipopedido
     */
    function delete_tipopedido($IDTipoPedido)
    {
        return $this->db->delete('TipoPedido',array('IDTipoPedido'=>$IDTipoPedido));
    }
}
