<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Up_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_imagem($IDImagem)
    {
        return $this->db->get_where('Up',array('IDImagem'=>$IDImagem))->row_array();
    }
    
    /*
     * Get unidade by IDImagens
     */
    function get_all_imagens()
    {
        $this->db->order_by('IDImagem', 'desc');
        return $this->db->get('up')->result_array();  
    }
    
    /*
     * function to add new unidade
     */
    function add_imagem($params)
    {                     //nome da tabela
        $this->db->insert('up',$params);
        return $this->db->insert_id();
    }
    
    function delete_imagem($IDImagem)
    {
        return $this->db->delete('Up',array('IDImagem'=>$IDImagem));
    }
    
    
}
